export const data = [
    {
      id: 1,
      name: "Harry Potter ve Felsefe Taşı",
      image:"https://upload.wikimedia.org/wikipedia/tr/9/93/Harry_Potter_ve_Felsefe_Ta%C5%9F%C4%B1.jpg",
      bilgi:["Harry Potter privet drive 4 numarada teyzesi eniştesi ve kuzeni ile birlikte yaşamaktadır. Annesi ve babasını bir trafik kazasında kaybettiğini sanıyordur. Dursleyler Harry’i hiç sevmezler çünkü onun büyücü olduğunu biliyorlardır ama bundan daha Harry’nin haberi yoktur.Bir gün Harry’e hogwarts büyücülük ve cadı yetiştirme okuluna kabul edildiğine dair  bir sürü mektup gelir.","Dursleyler Harry’nin bu mektubu okumasına engel olmak isteseler de Harry Potter sonunda birini okur. Daha sonra Hagrid onu alır ve Hogwarts’a giderler. Hagrid Harry’e annesi ve babasının trafik kazasında ölmediğini Voldemort adında kötü bir büyücü tarafından öldürüldüğünü ve alnındaki yara izinin sebebinin de o olduğunu anlatır. O Voldemort’tan kurtulan tek kişidir yani sağ kalan çocuktur. Hogwarts’a vardıktan sonra seçmen şapka ile nereye gidecekleri seçilir. Harry trende tanıştığı Ron ve Hermione ile birlikte Gryffindor’a seçilir.","Harry Ron ve Hermione değişen merdivenler yüzünden bir gün yanlışlıkla yasaklı bölüme girerler ve orada bir kapağın üstünde yatmış olan üç başlı bir köpek görürler. Onun orada bir şeyi koruduğunu düşünürler. Harry onun Hagrid’le birlikte alışverişleri sırasında bankadan aldıkları gizli şeyle ilgili olduğunu düşünür. Hagrid’e sormaya gittiklerinde Hagrid bunun onları ilgilendirmediğini bunun Nicholas Flamel’le ve Hogwarts’la ilgili olduğunu söyler."],
      link:"https://www.muhendisbeyinler.net/harry-potter-ve-felsefe-tasi-kitap-ozeti/#google_vignette",
    },
    {
      id: 2,
      name: "Harry Potter ve Sırlar Odası ",
      image:"https://upload.wikimedia.org/wikipedia/tr/e/e6/Harry_Potter_ve_S%C4%B1rlar_Odas%C4%B1_kitap_kapa%C4%9F%C4%B1.jpg",
      bilgi:["Harry Potter yaz tatilini üvey ailesi Dursley’lerle birlikte geçirmiş, bu tatil onun için işkenceye dönmüş ve bir an önce okula dönmek istemektedir. Bu sıralarda Harry’nin odasında Dobby adında ev cini belirmiş ve Harry’e eğer okula dönerse başına kötü şeyler geleceğini, ölebileceğini söyler. Dobby Harry’i korumak için onun okula gitmesini engellemeye çalışır ama başarılı olamaz. Harry Potter okula geldiğinde esrarengiz olaylarla karşılaşmaya başlar. İlk olarak Harry Potter çatal dilinde sesler duyar. Ses Harry’i kendisine doğru çağırır. Daha sonra Harry’i koridorda yürürken sesi tekrar duyar.","Ses Harry’e “Kan kokusu alıyorum, öldüreceğim öldüreceğim” der. Ardından Harry’i koşmaya başlar ve Filch’in kedisini taşa döndüğünü ve duvarda “Sırlar odası açıldı” yazısını görür. Bu yazının üzerine düşen Harry Ron ve Hermione sırlar odasının gizemini araştırmaya başlar. 1000 yıl öncesinde okulu kuran 4 kişiden biri olan Salazar Slytherin’in okula alımlarda daha seçici olunması gerektiğini söylüyor sadece saf kan büyücü olan kişilerin okula alınması gerektiğini söylüyordu. Ama diğerlerini ikna edemeyince okuldan ayrıldı. Okulda gizli bir yer inşa ediyor ve varisi gelene kadar kapıyı mühürlüyor. Sadece varis kapısını açabilecek içindeki dehşeti ortaya çıkartacak ve saf kan olmayan büyücüleri temizleyecektir.","Okulda taşa dönüşen kişi sayısı artınca bakanlık Dumbledore’u görevden alır ve Hagrit’i sırlar odasını açmakla suçlayıp Azkaban’a gönderirler. Harry’i kızlar tuvaletinde bir günlük bulur. Günlüğün üstünde Tom Marvolo Riddle yazmaktadır. Bu günlükte hiçbir şey yazmaz ama bu günlük Harry Potter ile konuşur. Harry Potter sırlar odası hakkında ne bildiğini günlüğe sorar ama yanıt alamaz. Günlük onu 50 sene önceye götürür. 50 sene önce sırlar odası tekrar açılmış ve bir muggle aileye sahip büyücünün ölmesiyle sonuçlanmıştır."],
      link:"https://www.muhendisbeyinler.net/harry-potter-ve-sirlar-odasi-kitap-ozeti/",
    },
    {
      id: 3,
      name: "Harry Potter ve Azkaban Tutsağı",
      image: "https://upload.wikimedia.org/wikipedia/tr/8/88/HarryAzkaban.jpg",
      bilgi:["Harry yaz tatilinde Dursley ailesinin yanındadır. Dursley ailesinin Marge adında misafirleri vardır. Marge hala Vernon eniştenin ablasıdır. Harry’nin anne ve babası hakkında ileri geri konuşurken Harry Potter sinirlenir ve Marge halayı uçan bir balona çevirir. Bu olaydan sonra Harry Dursley’lerin yanında kalmak istemez ve yanlarından ayrılır. Evden biraz uzaklaştıktan sonra bir duvarın kenarına oturur. Otururken karşısında siyah bir köpeğin ona baktığını görür. Korkar ve yere düşer. Ardından büyülü bir otobüse biner ve cadılar için dinlenme yeri olan Çatlakkazana doğru yola koyulur. Harry şaşkınlığını daha atlatamamışken biletçinin elinde tuttuğu gazetede bir haber görür."," Haberde, bir mahkumun  Azkaban tutsağından kaçtığı yazar. Kaçan mahkumun isminin Sirius Black olduğunu ve Voldemort’un destekçisi olduğunu öğrenir. Harry Çatlakkazana geldiğinde Bay Weasley ile karşılaşır. Bay Weasley, Harry’e Sirius Black’in Harry’i öldürmek için kaçtığını, onu öldürürse Voldemort’un tekrar güç kazanacağını söyler. Harry, Ron ve Hermione okula gitmek için trene bindiğinde tren aniden durur, etraf buz gibi olur. İçeri bir ruh emici girer ve Harry’nin ruhunu emmeye başlar. Profesör Lupin Harry ile aynı odadadır ve ruh emiciyi uzaklaştırır. Sihir bakanlığının aldığı karar üzerine Azkaban muhafızı olan ruh emiciler Hogwarts etrafında dolanacak ve Sirius Black’i yakalamaya çalışacaktır. Hagrid Sihirli Yaratıkların Bakımı Dersi’ne girmektedir.","Derste öğrencilerine Şahgaga isimli bir hipogrifi anlatır. Hipogrifler çok gururlu yaratıklardır. Öğrencilerini hipogriflere karşı kötü konuşmamaları için uyarır. Harry hipogrif ile iyi anlaşır. Malfoy bunu görünce Şahgaga’nın üstüne doğru yürür ve ona hakaret. Şah gaga kızar ve Malfoy’a vurur. Harry’i Sirius’un Hogwarts’ın yakınlarında bir kasabada görüldüğü haberini okur. Daha sonra tablodaki şişman kadının sakladığını görürler. Şişman kadın onlara Sirius Black’in okulda olduğu söyler. Fred ve George kardeşler Harry’e çapulcu haritasını verir. Bu harita herkesin nerede olduğunu gösteren bir harita. Harry Potter Profesör Mcgonagall’ı gizlice dinler. Sirius Black’in Harry’nin vaftiz babası olduğunu, anne ve babasının yakın dostu olduğunu, ailesine ihanet ederek ailesinin yerini Voldemort’a söylediğini, Peter Pettigrew adında arkadaşını öldürdüğünü duyar."],
      link:"https://www.muhendisbeyinler.net/harry-potter-ve-azkaban-tutsagi-kitap-ozeti/",
    },
    {
      id: 4,
      name: "Harry Potter ve Ateş Kadehi",
      image: "https://upload.wikimedia.org/wikipedia/tr/5/5f/Harry_Potter_ve_Ate%C5%9F_Kadehi_%28kitap%29.jpg",
      bilgi:["Harry Potter, rüyasında Voldemort, Peter Pettigrew ve daha önce görmediği bir adamı görür. Rüyada Voldemort insan bedeninde değildir. Voldemort Harry’nin tanımadığı adama Harry’i getirmesini söyler. Ron, Harry’i Dünya Quidditch Finaline çağırır. Her şey yolunda giderken ölüm yiyenler belirir. Ölüm yiyenler Muggleları terörize eder ve gökyüzünde karanlık işaret belirir. Harry, Sirius Black’e bir mektup yazar ve olaylardan bahseder. Bu sene iki farklı okulu misafir edecek Hogwarts’da üç büyücü turnuvası düzenlenecektir. Her okuldan yalnızca bir öğrenci seçilecektir. Seçilen öğrenci okulunu temsil edecektir. Bu yarışma için üç farklı okul bir araya gelmektedir.", "Bu okullar Beauxbatons, Durmstang ve Hogwarts’dır. Turnuvaya katılan öğrenciler üç zor görevi yerine getirmek zorunda. Ayrıca 17 yaşından küçük olanların turnuvaya katılmaları yasaklandı. Turnuvaya katılmak isteyen öğrenciler isimlerini bir kağıda yazıp ateş kadehine atmak zorunda. Bu sene okula Alestor Moody adında, Dumbledore’un ricası üzerine yeni bir Karanlık Sanatlara Karşı Savunma hocası gelmiştir. Perşembe gününün sonunda  Ateş Kadehi yazılan isimler içinden üç tane isim seçer. Beauxbatons’dan Fleur Delacour Durmstang’dan Viktor Krum Hogwarts’dan Cedric Diggory. Ama Ateş Kadeh’i son anda bir isim daha seçer, Harry Potter.","Kimse bu olaya anlam veremez çünkü Harry Potter 14 yaşındadır. Kuralsa kesindir: Ateş kadehinden çıkan isim yarışmakla yükümlüdür. Bu olaydan sonra Harry ve Ron’un arası açılır. Ron, Harry’nin ismini nasıl attığını söylemediği için konuşmamaktadır. Ama Harry hiçbir şeyden haberi olmadığını, ismini yazmadığını söyler. Sirius Black kendisini közde ortaya çıkarır ve Harry ile konuşur. Harry’e Profesör Karkaroff’un eskiden ölüm yiyen olduğunu; insanların kolay kolay değişmeyeceğini, dikkat etmesi gerektiğini söyler. Hagrid, Harry’e ilk yarışmanın ejderhalarla ilgili olduğunu söyler. Bu ilk görevdir. "],
      link:"https://www.muhendisbeyinler.net/harry-potter-ve-ates-kadehi-kitap-ozeti/#google_vignette",
    },
    {
      id: 5,
      name: "Harry Potter ve Zümrüdüanka Yoldaşlığı",
      image: "https://upload.wikimedia.org/wikipedia/tr/7/7f/Hp_z%C3%BCmr%C3%BCd%C3%BCanka_yolda%C5%9Fl%C4%B1%C4%9F%C4%B1.jpg",
      bilgi:["Harry Potter, Dursley ailesiyle geçirdiği yaz tatili boyunca ne sınıf arkadaşlarından ne de en yakın dostları Ron Weasley ve Hermione Granger'dan tek bir mektup almıştır. Bu yüzden Harry için yaz uzun ve yalnız geçmiştir.Yaz tatili için teyzesi ve eniştesi ile birlikte kalırken ruh emicilerin saldırısına uğrar. Harry kendisini ve kuzeni Dudley'i koruyabilmek için birPatronus büyüsü yapar. Bu olaydan hemen sonra Harry, teyzesinin komşusu Arabella Figg'in bir kofti olduğunu ve Dumbledore tarafından onu korumak için görevlendirildiğini öğrenir. Genç Yaşta Büyücülüğün Makul Kısıtlanması Kararnamesi'nden dolayı Sihir Bakanlığı, Harry'i bir duruşmaya çağırır ve belki de Harry Hogwarts'dan atılacaktır.","Bir gece Dumbledore emriyle aralarında Alastor ‘Deli-Göz’ Moody, Kingsley Shacklebolt ve Nymphadora Tonks’un da bulunduğu bir grup Seherbaz (Kara büyücü avcıları) Harry’nin kapısına gelip, Dumbledore’un, Sihir Bakanlığı’nda resmi bir temyiz duruşması ayarladığını söyleyerek, genç büyücüyü apar topar, vaftiz babası Sirius'un Grimmauld Meydanı 12 numaradaki evine götürürler. Bu ev aynı zamandaZümrüdüanka Yoldaşlığı'nın gizli karargâhıdır. Sirius toplantılar için ailesinin evini Zümrüdüanka Yoldaşlığı’na açmıştır.","Harry, Moody'nin gösterdiği eski fotoğrafla annesiyle babasının da Zümrüdüanka Yoldaşlığı’nın ilk üyelerinden olduğunu ve şu anki örgüt üyeleri arasında Molly ve Arthur Weasley’nin, Remus Lupin’in, Severus Snape’in ve şaşkınlık ve memnuniyetle karşıladığı vaftiz babası Sirius Black’in de bulunduğunu öğrenir. Harry’nin duruşmadaki tek umudu, genç büyücünün temelli gitmesini istemek için kendince sebepleri olan Sihir Bakanı Cornelius Fudge’ın yönettiği kurmaca mahkemede kendini savunmaktır. Harry, büyük ölçüde Hogwarts’ın emektar müdürü Albus Dumbledore’un müdahalesiyle ve tanık Arabella Figg sayesinde suçsuz bulunarak Fudge’ı çok üzer, ama ilk kez okuluna dönerken kaygılı ve huzursuzdur."],
      link:"https://oyuncularsehri.com/konu/harry-potter-ve-zumruduanka-yoldasligi-ozeti.751/",
    },
    {
      id: 6,
      name: "Harry Potter ve Melez Prens ",
      image: "https://upload.wikimedia.org/wikipedia/tr/e/e6/Harry_Potter_ve_Melez_Prens_kitap_kapa%C4%9F%C4%B1.jpeg",
      bilgi:["Voldemort’un gücüne geri dönmüş, öfkesi hem Muggle hem de Büyücü dünyasında hissedilmiştir. Severus Snape, uzun süredir Voldemort’un düşmanı olarak kabul edilen ve Dumbledore’un anti-Voldemort koalisyonu olan Fönix Düzeni’nin bir üyesi olan Narcissa Malfoy ile buluşur. Narcissa, Draco’nun annesi ve Lucius’un (bir hapsedilmiş Death Eater) eşidir. Snape, Draco’yu koruma sözü vererek Narcissa’ya karşı kırılmaz bir yemin yapar.","Dumbledore, Harry’yi teyzesinden ve amcasından almak için 4 Privet Drive’a gider. Yolda Burrow’a giderken, Harry Potter ve Dumbledore, Horace Slughorn’u Hogwarts’ta tekrar öğretmenlik yapmaya ikna etmek için durur. Harry, en iyi arkadaşları Ron ve Hermione ile tekrar bir araya gelir. Harry, okul kitapları için alışveriş yaparken Draco ile karşılaşır ve onu Borgin and Burkes’e takip eder; burada Draco’nun Borgin’i tehdit ettiğini ve bilinmeyen bir nesneyi tamir etmesini istediğini duyar. Harry hemen Draco’ya şüpheyle bakar, çünkü onu babası gibi bir Death Eater olarak düşünür. Öğrenciler okula döner ve Dumbledore, Snape’in Karanlık Sanatlara Karşı Savunma Dersi öğreteceğini açıklar, bu da Harry’i şaşırtır.","Harry Potter , bir zamanlar “Melez Prens” adında birine ait olan kullanılmış bir İksirler kitabı alır. Kitabın kenarlarına büyüler ve düzeltmeler yazılmıştır ve Harry, İksirler dersinde başarılı olmak için Prens’in notlarını kullanır. Dumbledore, Harry ile düzenli toplantılar düzenler; bu toplantılarda Dumbledore’un Pensieve’ını kullanarak Voldemort ile doğrudan teması olanların anılarına bakarlar. Dumbledore, Harry’nin Voldemort’un geçmişi hakkında yeterince bilgi edinmesinin, nihayet yüz yüze savaştıklarında ona yardımcı olacağına inanır, çünkü Harry’yi ilgilendiren kehanet öyle söyler."],
      link:"https://www.kitapoozetleri.com/harry-potter-ve-melez-prens-ozet",
    
    },
    {
      id: 7,
      name: "Harry Potter ve Ölüm Yadigârları",
      image: "https://upload.wikimedia.org/wikipedia/tr/2/23/Harry_Potter_ve_%C3%96l%C3%BCm_Yadig%C3%A2rlar%C4%B1.jpg",
      bilgi:[" Ölüm Yiyenler Harry' i 17 yaşına girdiğinde öldürmek isterler. Ölüm Yiyenler, Zümrüdüanka Yoldaşlığı' nın Harry'i almaya geleceğini öğrenirler. Zümrüdüanka Yoldaşlığı geldiğinde ilk önce Dursley ailesini güvenli bir yere götürürler. Zümrüdüanka Yoldaşlığı çok özlü iksir içerek Harry' nin kılığına girerler. Daha sonra Harry' i götürmeye çalışırlar fakat fazla gidemeden Ölüm Yiyenler saldırır. Harry' nin baykuşu Hedwig saldırıda ölür. Harry ne olduğunu anlayamadan Voldemort gelir. Önce Profesör Moody' i öldürür. Harry' e saldırır fakat Harry' nin asası kendi başına sihir yapar. Harry çok şaşırır. Daha sonra Kovuk' a varırlar.","   Birkaç gün sonra Kovukta otururlarken Sihir Bakanı Rufus Scrimgeour ve Percy Weasley gelir. Dumbledore Harry, Ron ve Hermione' ye ölmeden önce birkaç eşya bırakmıştır. Rufus Scrimgeour bunları dağıtır. Harry' e Quidditch maçında ilk tuttuğu Snitch' i ve Gryffindor' un kılıcını, Ron' a bir ışık emer ve Hermione' ye bir kitap bırakmıştır. Fakat Gryffindor' un kılıcı Harry' e verilmez. Çünkü kılıç hem okulun malıdır hem de nerede olduğu bilinmemektedir.", 
      "Bill ve Fleur' un düğün vakti gelmiştir. Düğün sonunda Sihir Bakanını koruyan ve aynı zamanda Zümrüdüanka yoldaşlığı üyesi olan Kingsley Shacklebolt Sihir Bakanının öldüğünü ve Ölüm Yiyenlerin düğüne gelmek üzere olduğunu söyler. Dediği doğru çıkar. Aradan dakikalar geçmemişken Ölüm Yiyenler gelir. "],
      link:"https://ozetcimiz.blogspot.com/2015/12/harry-potter-ve-olum-yadigarlar.html",
    },    
      
    ];