export const data = [
    {
      id: 1,
      title: "Hogwarts Kar Küresi",
      category:"accessory",
      image:"/img/HogwartsKarKuresi699.png",
      images:["/img/HogwartsKarKuresi699.png"],
      price:699.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ", 
    },
    {
      id: 2,
      title: "Tasarım Kupa",
      category:"accessory",
      image:"/img/gozluksimsektasarimliKupa229.png",
      images:["/img/gozluksimsektasarimliKupa229.png"],
      price:299.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 3,
      title: "Harry Potter Kitapları Seti",
      category:"books",
      image:"/img/kitapSeti1735.png",
      images:["/img/kitapSeti1735.png"],
      price:1734.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 4,
      title: "Seçmen Şapka",
      category:"accessory",
      image:"/img/secmensapka499.png",
      images:["/img/secmensapka499.png"],
      price:499.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 5,
      title: "Çizgili Defter",
      category:"books",
      image:"/img/Deftercizgili149.png",
      images:["/img/Deftercizgili149.png"],
      price:149.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 6,
      title: "Tek Kişilik Nevresim Takımı",
      category:"accessory",
      image:"/img/MagicSquadTekNevresim1258.png",
      images:["/img/MagicSquadTekNevresim1258.png"],
      price:1249.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 7,
      title: "Sweatshirt ",
      category:"clothes",
      image:"/img/Sweatshirt699.png",
      images:["/img/Sweatshirt699.png"],
      price:699.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 8,
      title: "Fosforlu Kalem",
      category:"books",
      image:"/img/fosforlukalem216.png",
      images:["/img/fosforlukalem216.png"],
      price:214.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 9,
      title: "Kapı Önü Paspası",
      category:"accessory",
      image:"/img/paspas349.png",
      images:["/img/paspas349.png"],
      price:349.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 10,
      title: "Baskılı Çorap Seti",
      category:"clothes",
      image:"/img/corapSeti269.png",
      images:["/img/corapSeti269.png"],
      price:269.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 11,
      title: "Özel Kutulu Metal Asa Seti",
      category:"accessory",
      image:"/img/ozelKutuluMetalAsaSeti1500.png",
      images:["/img/ozelKutuluMetalAsaSeti1500.png"],
      price:1499.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 12,
      title: "Baskılı Telefon Kılıfı",
      category:"accessory",
      image:"/img/telefonkilifi279.png",
      images:["/img/telefonkilifi279.png"],
      price:279.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 13,
      title: "Harry Potter Yemek Kitabı",
      category:"books",
      image:"/img/harryPotterYemekKitabi280.png",
      images:["/img/harryPotterYemekKitabi280.png"],
      price:299.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 14,
      title: "Baskılı Beyaz Tişört",
      category:"clothes",
      image:"/img/beyazTisort230.png",
      images:["/img/beyazTisort230.png"],
      price:229.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
    {
      id: 15,
      title: "Hogwarts Kar Küresi",
      category:"accessory",
      image:"/img/Kupa330mlLacivert300.png",
      images:["/img/Kupa330mlLacivert300.png"],
      price:299.99,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt, magni ducimus facilis debitis voluptatum saepe iure, a voluptas minus aspernatur impedit officia dolorem? Dolores quaerat similique quisquam repellendus aspernatur. Quasi. ",
    },
]